[package]
name = "cli"
version = "0.0.2"
authors = ["slundi"]
edition = "2024"
description = "Rust command line interface (CLI) for guitar tab files."
repository = "https://gitlab.com/slundi/guitar-io"
license = "MIT"
readme = "README.md"

[[bin]]
name = "score_tool"
path = "src/main.rs"

[dependencies]
guitarpro = { path = "../guitarpro" }
bpaf = { version = "0.9", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
quick-xml = { version = "0.41", features = ["serialize"] }

[dev-dependencies]
