//! Named MSCZ fixtures for Part 5 of the roadmap.
//!
//! Each fixture is a hand-written MSCX document exercising a distinct
//! MuseScore 4.10 shape (monophonic guitar, multi-track band, alternate
//! tuning, repeats/voltas, edge cases). The `build_fixture` helper wraps
//! the MSCX body into an MSCZ ZIP container.
//!
//! The catalog is also mirrored on disk at `guitarpro/samples/mscz/`
//! (regenerated by the `write_mscz_samples_to_disk` test); those files
//! are what the CLI and web-server integration tests consume. Nothing in
//! the catalog is derived from a copyrighted score.
//!
//! # Public helpers (test-only)
//!
//! * `FIXTURES` — the ordered `(name, mscx_body)` catalog.
//! * `build_fixture(name)` — produces `.mscz` bytes for a named fixture.
//! * `sample_dir()` — absolute path to `guitarpro/samples/mscz/`.
//! * `write_mscz_samples_to_disk` — `#[test] #[ignore]` that regenerates
//!   the on-disk sample set. Run with `cargo test -p guitarpro
//!   write_mscz_samples_to_disk -- --ignored --exact`.

use std::io::Write;
use std::path::PathBuf;

use zip::write::SimpleFileOptions;
use zip::{CompressionMethod, ZipWriter};

// ---------------------------------------------------------------------------
// Catalog
// ---------------------------------------------------------------------------

/// The full fixture catalog, ordered so downstream tests reporting
/// "N/N ✓" always list fixtures in the same order.
pub const FIXTURES: &[(&str, &str)] = &[
    ("simple_monophonic", SIMPLE_MONOPHONIC),
    ("multi_track_band", MULTI_TRACK_BAND),
    ("alternate_tuning", ALTERNATE_TUNING),
    ("repeats_and_voltas", REPEATS_AND_VOLTAS),
    ("empty_score", EMPTY_SCORE),
    ("single_measure", SINGLE_MEASURE),
    ("four_voices", FOUR_VOICES),
];

const CONTAINER_XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<container>
  <rootfiles>
    <rootfile full-path="score.mscx"/>
    </rootfiles>
  </container>
"#;

// ---------------------------------------------------------------------------
// Fixture bodies
// ---------------------------------------------------------------------------

/// Solo guitar line: two measures of quarter notes (Em → G) in 4/4 at ♩=120.
const SIMPLE_MONOPHONIC: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.10">
  <programVersion>4.2.0</programVersion>
  <programRevision>fixture</programRevision>
  <Score>
    <Division>480</Division>
    <metaTag name="workTitle">Simple Monophonic Fixture</metaTag>
    <metaTag name="composer">guitar-io fixtures</metaTag>
    <metaTag name="copyright">Public Domain</metaTag>
    <Part id="1">
      <Staff id="1">
        <StaffType group="pitched"><name>stdNormal</name></StaffType>
        <defaultClef>G</defaultClef>
        </Staff>
      <trackName>Classical Guitar</trackName>
      <Instrument id="pluck.guitar.classical">
        <longName>Classical Guitar</longName>
        <shortName>c.g.</shortName>
        <instrumentId>pluck.guitar.classical</instrumentId>
        <StringData>
          <frets>19</frets>
          <string>40</string><string>45</string><string>50</string>
          <string>55</string><string>59</string><string>64</string>
          </StringData>
        </Instrument>
      </Part>
    <Staff id="1">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <KeySig><accidental>0</accidental></KeySig>
          <Tempo><tempo>2.0</tempo></Tempo>
          <Chord><durationType>quarter</durationType><Note><pitch>52</pitch><tpc>18</tpc></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>55</pitch><tpc>15</tpc></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>59</pitch><tpc>16</tpc></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>62</pitch><tpc>17</tpc></Note></Chord>
          </voice>
        </Measure>
      <Measure>
        <voice>
          <Chord><durationType>quarter</durationType><Note><pitch>55</pitch><tpc>15</tpc></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>59</pitch><tpc>16</tpc></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>62</pitch><tpc>17</tpc></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>67</pitch><tpc>15</tpc></Note></Chord>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"#;

/// Three-track band: guitar (tab), bass (4-string), drum kit (percussion).
const MULTI_TRACK_BAND: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.10">
  <programVersion>4.2.0</programVersion>
  <Score>
    <Division>480</Division>
    <metaTag name="workTitle">Multi-Track Band Fixture</metaTag>
    <metaTag name="composer">guitar-io fixtures</metaTag>
    <Part id="1">
      <Staff id="1">
        <StaffType group="tablature"><name>tab6StrCommon</name></StaffType>
        <defaultClef>G8vb</defaultClef>
        </Staff>
      <trackName>Guitar</trackName>
      <Instrument id="pluck.guitar.electric">
        <longName>Electric Guitar</longName>
        <shortName>e.g.</shortName>
        <instrumentId>pluck.guitar.electric</instrumentId>
        <StringData>
          <frets>24</frets>
          <string>40</string><string>45</string><string>50</string>
          <string>55</string><string>59</string><string>64</string>
          </StringData>
        </Instrument>
      </Part>
    <Part id="2">
      <Staff id="2">
        <StaffType group="pitched"><name>stdNormal</name></StaffType>
        <defaultClef>F</defaultClef>
        </Staff>
      <trackName>Bass</trackName>
      <Instrument id="pluck.bass-guitar">
        <longName>Electric Bass</longName>
        <shortName>e.b.</shortName>
        <instrumentId>pluck.bass-guitar</instrumentId>
        <StringData>
          <frets>24</frets>
          <string>28</string><string>33</string><string>38</string><string>43</string>
          </StringData>
        </Instrument>
      </Part>
    <Part id="3">
      <Staff id="3">
        <StaffType group="pitched"><name>stdNormal</name></StaffType>
        <defaultClef>PERC</defaultClef>
        </Staff>
      <trackName>Drum Kit</trackName>
      <Instrument id="drum.kit">
        <longName>Drum Kit</longName>
        <shortName>dr.</shortName>
        <instrumentId>drum.kit</instrumentId>
        </Instrument>
      </Part>
    <Staff id="1">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Tempo><tempo>2.0</tempo></Tempo>
          <Chord><durationType>quarter</durationType>
            <Note><pitch>52</pitch><string>4</string><fret>2</fret></Note>
            </Chord>
          <Chord><durationType>quarter</durationType>
            <Note><pitch>55</pitch><string>3</string><fret>0</fret></Note>
            </Chord>
          <Rest><durationType>half</durationType></Rest>
          </voice>
        </Measure>
      </Staff>
    <Staff id="2">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Chord><durationType>quarter</durationType>
            <Note><pitch>28</pitch><string>3</string><fret>0</fret></Note>
            </Chord>
          <Rest><durationType>quarter</durationType></Rest>
          <Rest><durationType>half</durationType></Rest>
          </voice>
        </Measure>
      </Staff>
    <Staff id="3">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Rest><durationType>measure</durationType></Rest>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"#;

/// Guitar in Drop-D tuning (D2 A2 D3 G3 B3 E4) with a whole-measure chord.
const ALTERNATE_TUNING: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.10">
  <programVersion>4.2.0</programVersion>
  <Score>
    <Division>480</Division>
    <metaTag name="workTitle">Alternate Tuning Fixture</metaTag>
    <metaTag name="composer">guitar-io fixtures</metaTag>
    <Part id="1">
      <Staff id="1">
        <StaffType group="tablature"><name>tab6StrCommon</name></StaffType>
        <defaultClef>G8vb</defaultClef>
        </Staff>
      <trackName>Drop D Guitar</trackName>
      <Instrument id="pluck.guitar.acoustic">
        <longName>Acoustic Guitar (Drop D)</longName>
        <shortName>a.g.</shortName>
        <instrumentId>pluck.guitar.acoustic</instrumentId>
        <StringData>
          <frets>19</frets>
          <string>38</string><string>45</string><string>50</string>
          <string>55</string><string>59</string><string>64</string>
          </StringData>
        </Instrument>
      </Part>
    <Staff id="1">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Tempo><tempo>1.6</tempo></Tempo>
          <Chord><durationType>whole</durationType>
            <Note><pitch>38</pitch><string>5</string><fret>0</fret></Note>
            <Note><pitch>50</pitch><string>3</string><fret>0</fret></Note>
            <Note><pitch>57</pitch><string>2</string><fret>2</fret></Note>
            <Note><pitch>62</pitch><string>1</string><fret>3</fret></Note>
            </Chord>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"#;

/// Repeat structure: `|: bar1 → bar2 :| bar3` with `endRepeat>3`.
const REPEATS_AND_VOLTAS: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.10">
  <programVersion>4.2.0</programVersion>
  <Score>
    <Division>480</Division>
    <metaTag name="workTitle">Repeats And Voltas Fixture</metaTag>
    <metaTag name="composer">guitar-io fixtures</metaTag>
    <Part id="1">
      <Staff id="1">
        <StaffType group="pitched"><name>stdNormal</name></StaffType>
        <defaultClef>G</defaultClef>
        </Staff>
      <trackName>Guitar</trackName>
      <Instrument id="pluck.guitar.electric">
        <longName>Electric Guitar</longName>
        <shortName>e.g.</shortName>
        <instrumentId>pluck.guitar.electric</instrumentId>
        <StringData>
          <frets>24</frets>
          <string>40</string><string>45</string><string>50</string>
          <string>55</string><string>59</string><string>64</string>
          </StringData>
        </Instrument>
      </Part>
    <Staff id="1">
      <Measure>
        <startRepeat/>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Tempo><tempo>2.0</tempo></Tempo>
          <Rest><durationType>measure</durationType></Rest>
          </voice>
        </Measure>
      <Measure>
        <voice>
          <Rest><durationType>measure</durationType></Rest>
          </voice>
        </Measure>
      <Measure>
        <endRepeat>3</endRepeat>
        <voice>
          <Rest><durationType>measure</durationType></Rest>
          </voice>
        </Measure>
      <Measure>
        <voice>
          <Rest><durationType>measure</durationType></Rest>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"#;

/// One track, one measure of pure rest — the empty-score edge case.
const EMPTY_SCORE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.10">
  <programVersion>4.2.0</programVersion>
  <Score>
    <Division>480</Division>
    <metaTag name="workTitle">Empty Score Fixture</metaTag>
    <Part id="1">
      <Staff id="1">
        <StaffType group="pitched"><name>stdNormal</name></StaffType>
        <defaultClef>G</defaultClef>
        </Staff>
      <trackName>Silence</trackName>
      <Instrument id="pluck.guitar.classical">
        <longName>Classical Guitar</longName>
        <instrumentId>pluck.guitar.classical</instrumentId>
        </Instrument>
      </Part>
    <Staff id="1">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Rest><durationType>measure</durationType></Rest>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"#;

/// A single-measure score — smallest non-empty fixture.
const SINGLE_MEASURE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.10">
  <programVersion>4.2.0</programVersion>
  <Score>
    <Division>480</Division>
    <metaTag name="workTitle">Single Measure Fixture</metaTag>
    <Part id="1">
      <Staff id="1">
        <StaffType group="pitched"><name>stdNormal</name></StaffType>
        <defaultClef>G</defaultClef>
        </Staff>
      <trackName>Guitar</trackName>
      <Instrument id="pluck.guitar.classical">
        <longName>Classical Guitar</longName>
        <instrumentId>pluck.guitar.classical</instrumentId>
        </Instrument>
      </Part>
    <Staff id="1">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Chord><durationType>whole</durationType>
            <Note><pitch>60</pitch><tpc>14</tpc></Note>
            </Chord>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"#;

/// One measure carrying four `<voice>` blocks — MuseScore's per-measure voice cap.
const FOUR_VOICES: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.10">
  <programVersion>4.2.0</programVersion>
  <Score>
    <Division>480</Division>
    <metaTag name="workTitle">Four Voices Fixture</metaTag>
    <Part id="1">
      <Staff id="1">
        <StaffType group="pitched"><name>stdNormal</name></StaffType>
        <defaultClef>G</defaultClef>
        </Staff>
      <trackName>Piano RH</trackName>
      <Instrument id="keyboard.piano">
        <longName>Piano</longName>
        <instrumentId>keyboard.piano</instrumentId>
        </Instrument>
      </Part>
    <Staff id="1">
      <Measure>
        <voice>
          <TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig>
          <Chord><durationType>quarter</durationType><Note><pitch>72</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>72</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>72</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>72</pitch></Note></Chord>
          </voice>
        <voice>
          <Chord><durationType>quarter</durationType><Note><pitch>67</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>67</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>67</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>67</pitch></Note></Chord>
          </voice>
        <voice>
          <Chord><durationType>quarter</durationType><Note><pitch>64</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>64</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>64</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>64</pitch></Note></Chord>
          </voice>
        <voice>
          <Chord><durationType>quarter</durationType><Note><pitch>60</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>60</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>60</pitch></Note></Chord>
          <Chord><durationType>quarter</durationType><Note><pitch>60</pitch></Note></Chord>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"#;

// ---------------------------------------------------------------------------
// Builders
// ---------------------------------------------------------------------------

/// Pack a given MSCX body into a minimal MSCZ archive
/// (`META-INF/container.xml` + `score.mscx`). Deterministic byte order per
/// invocation, but ZIP timestamps come from the current clock.
pub fn wrap_mscz(mscx: &str) -> Vec<u8> {
    let cursor = std::io::Cursor::new(Vec::new());
    let mut writer = ZipWriter::new(cursor);
    let deflate = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

    writer
        .start_file("META-INF/container.xml", deflate)
        .expect("write container.xml");
    writer
        .write_all(CONTAINER_XML.as_bytes())
        .expect("container payload");

    writer
        .start_file("score.mscx", deflate)
        .expect("write score.mscx");
    writer.write_all(mscx.as_bytes()).expect("mscx payload");

    writer.finish().expect("finalize zip").into_inner()
}

/// Return the MSCZ bytes for the named fixture, or `None` if `name`
/// is not in [`FIXTURES`].
pub fn build_fixture(name: &str) -> Option<Vec<u8>> {
    FIXTURES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, mscx)| wrap_mscz(mscx))
}

/// Absolute path to `guitarpro/samples/mscz/`, computed from the crate
/// manifest dir so the tests are hermetic regardless of the working
/// directory the test runner is invoked from.
pub fn sample_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("samples")
        .join("mscz")
}

// ---------------------------------------------------------------------------
// Regeneration test (ignored by default)
// ---------------------------------------------------------------------------

/// Rewrite every fixture in [`FIXTURES`] to `guitarpro/samples/mscz/`.
///
/// Committed once so the CLI and web-server tests (and manual inspection
/// via `unzip`) always have a stable set of MSCZ files to consume. Run
/// with:
///
/// ```sh
/// cargo test -p guitarpro write_mscz_samples_to_disk -- --ignored --exact
/// ```
#[test]
#[ignore]
fn write_mscz_samples_to_disk() {
    let dir = sample_dir();
    std::fs::create_dir_all(&dir).expect("create samples dir");
    for (name, _) in FIXTURES {
        let bytes = build_fixture(name).expect("named fixture must exist");
        let path = dir.join(format!("{name}.mscz"));
        std::fs::write(&path, &bytes).expect("write fixture");
        eprintln!("wrote {} ({} bytes)", path.display(), bytes.len());
    }
}
